### ISSUE TITLE
【RFC】关于ventus的gnu工具链支持

### ISSUE THREAD

**Issue by TuringKi** [THU-DSP-LAB/ventus-gpgpu#29]
在异构计算方面，目前gnu只对amdgcn与nvptx做了支持，他们都是闭源的硬件平台。gnu缺乏对一个完整公开的gpgpu的支持。虽然之前有一些工作(https://github.com/pulp-platform/hero)，但是后续似乎都转向了基于llvm的方案。
ventus-gpgpu 是一个雄心勃勃的计划，如果在开发过程中，同步支持gnu的gcc/gomp与llvm/opencl的方案，并在完善后合入gcc主线，这对于开放的异构计算研究将是个很好的消息。
目前，作为个人开发者，我最近在尝试做这方面的工作：

https://github.com/mxlol233-ventus/gcc/issues/1
https://github.com/orgs/mxlol233-ventus/repositories

但是ventus公开的文档比较欠缺，同时我也想与您的项目组保持沟通，并对未来的计划有更详细的了解。所以，想请问下是否存在更加完善的资料，或者工作群可以加一下？

**Comment by hehu-tsinghua** [comment]
[非常感谢你对ventus-gpgpu的支持。我们开发llvm/opencl方案就是用的白皮书的内容。应该已经包括了编译器需要的全部信息。如果您觉得还缺少所需要的信息，可以给我们发issue，我们会补充完善白皮书内容。谢谢！[https://github.com/THU-DSP-LAB/ventus-gpgpu-doc](url)
