### ISSUE TITLE
Chisel 3.6+ Support

### ISSUE THREAD

**Issue by sequencer** [THU-DSP-LAB/ventus-gpgpu#31]
Chisel will shortly end support to 3.5.X, suggesting upgrade Chisel versions to Chisel 5/6, and migrate to CIRCT flow.

**Comment by liuxd17thu** [comment]
Our project still has a bunch of dependencies based on Chisel 3.x, so there should be a lot of work to do.
BTW, I wonder if there are solutions to make chisel3 modules and chisel 5/6 modules work together.
------
我们项目里还有若干依赖还是Chisel3的，不太好解决。
查阅了一下资料，似乎没有在项目中混合使用Chisel3和Chisel5/6硬件模块的方案？

**Comment by reoLantern** [comment]
Currently working on bumping to chisel 6.4.0

**Comment by reoLantern** [comment]
currently chisel 6.4.0 is supported at branch dev-2024
