### ISSUE TITLE
make test报错   commit:  19dc44a7529198411a7ed5b17d19443d545bddd2

### ISSUE THREAD

**Issue by xiaoyu1004** [THU-DSP-LAB/ventus-gpgpu#32]
![image](https://github.com/THU-DSP-LAB/ventus-gpgpu/assets/80047235/5411d282-5111-4e6d-8bf0-970d925a0335)
我做了如下修改能跑了，不知道改的对不对
![image](https://github.com/THU-DSP-LAB/ventus-gpgpu/assets/80047235/3e94ff9c-d5f3-4b88-b76b-3619dd60b0bf)
![image](https://github.com/THU-DSP-LAB/ventus-gpgpu/assets/80047235/a3845633-0635-4673-a630-0f369c0f11a8)

**Comment by reoLantern** [comment]
make test问题，已经修改成play.AdvancedTest
