### ISSUE TITLE
saxpy2 test error

### ISSUE THREAD

**Issue by xiaoyu1004** [THU-DSP-LAB/ventus-gpgpu#33]
指令还未执行完就报错，vfmacc.vf执行完后pc值为undefine
![image](https://github.com/THU-DSP-LAB/ventus-gpgpu/assets/80047235/daa6eeda-f9ed-4e65-a8da-ccd97a7e3ffe)

**Comment by willdla** [comment]
遇到了同样的错误

**Comment by reoLantern** [comment]
Makefile中test下的play.hello_test2应该修改为play.AdvancedTest

**Comment by willdla** [comment]
> Makefile中test下的play.hello_test2应该修改为play.AdvancedTest

确实 

./mill -i ventus.tests.testOnly play.AdvancedTest

就可以跑了
代码在 ventus/tests/src/tests.scala

**Comment by reoLantern** [comment]
之前的hello_test2太老了，应该是没有再维护，GPU测例都通过AdvancedTest测试，测例文件在txt文件夹
