### ISSUE TITLE
fpga_test

### ISSUE THREAD

**Issue by lzone666** [THU-DSP-LAB/ventus-gpgpu#38]
1、make bsp生成的GPGPU_top.v与GPGPU_axi_top接口完全不同；
2、有没有最新版本的GPGPU_axi_adapter.v与其适配；
3、是否支持fpga_test？

**Comment by yangzexia** [comment]
需要在ventus-gpgpu/ventus/src/top/ExtMem_gen.scala:24这里，将`GPGPU_top`改为`GPGPU_axi_top`
