### ISSUE TITLE
How to generate .data file

### ISSUE THREAD

**Issue by RichardRo** [THU-DSP-LAB/ventus-gpgpu#55]
Hi,
With llvm compiler, elf file can be generated. Want to know how to generate .data file. Thanks.

**Comment by reoLantern** [comment]
We use the [Spike simulator](https://github.com/THU-DSP-LAB/ventus-gpgpu-isa-simulator) to generate .metadata and .data files that can be run by the Chisel project. After configuring the entire environment of the [llvm-project](https://github.com/THU-DSP-LAB/llvm-project), running the compiled executable will generate .metadata and .data files in the same directory.

**Comment by RichardRo** [comment]
Following llvm-project building steps, I'm able to generate .data and .metadata files now, thanks so much.
