### ISSUE TITLE
How to generate .data .metadata file for tensor cores?

### ISSUE THREAD

**Issue by RichardRo** [THU-DSP-LAB/ventus-gpgpu#64]
Hi, want to write some opencl code and run on tensor core, is there any guide to generate .data .metadata file for tensor core? Thanks.

**Comment by reoLantern** [comment]
Now tensor core is under branch dev-tc-v2, and currently test cases can only be generated by writing `asm volatile(".insn ... ")`. @liuweibupt Please explain the details.

**Comment by liuweibupt** [comment]
Currently, there are relevant test cases for tensor core in Ventus that can be referenced at https://github.com/liuweibupt/Ventus-OpenCL-Testcase/tree/main/_get_case/mma_new . Here, I provide test cases that we hope will be helpful to you.

**Comment by liuweibupt** [comment]
Specifically, you can use the Ventus software toolchain (https://github.com/THU-DSP-LAB/llvm-project) to compile OpenCL code and generate .metadata and .data files.

**Comment by RichardRo** [comment]
Will refer to the tensor core test cases, thank you.
