### ISSUE TITLE
请问能否详细描述一下opencl和gpu的关系

### ISSUE THREAD

**Issue by c4midori** [THU-DSP-LAB/ventus-gpgpu#66]
### Discussed in https://github.com/orgs/THU-DSP-LAB/discussions/65

<div type='discussions-op-text'>

<sup>Originally posted by **c4midori** October 30, 2024</sup>
我看了ventus-gpgpu-master中的代码和文档，已经了解了gpgpu的结构和怎么针对rtl进行仿真。但是我对怎么使用opencl还是不理解，不知道opencl编译出来的代码怎么执行。
能不能专门写个文档，描述一下opencl编译出来的代码是怎么在gpu上运行的？</div>

**Comment by reoLantern** [comment]
好的，因为不是纯硬件问题，后续在discussion中进行吧
