### ISSUE TITLE
verilator仿真波形为空

### ISSUE THREAD

**Issue by xiaokaijia1988** [THU-DSP-LAB/ventus-gpgpu#67]
在sim_main.cpp 中#define SIM_WAVEFORM_FST 修改成1，生成的Vdut.fst波形用gdkwave打开，只有信号名称，没有产生打波形。请问还有其他地方需要修改吗？
![截图 2024-10-30 20-41-24](https://github.com/user-attachments/assets/640e0ddc-8098-4f32-9582-b89a5e2004bb)

下面是log信息：
Time@316964:  block30 finished (kernel 0 matadd block30)
Time@320000:  Simulation cycles: 320000
Time@330000:  Simulation cycles: 330000
Time@334650:  block21 finished (kernel 0 matadd block21)
Time@338992:  block31 finished (kernel 0 matadd block31)
Time@338992:  kernel 0 matadd finished
Time@338992:  Simulation finished in 338992 cycles
- S i m u l a t i o n   R e p o r t: Verilator 5.029 devel
- Verilator: end at 339ns; walltime 30.667 s; speed 1.141 ns/s
- Verilator: cpu 297.143 s on 10 threads; alloced 174 MB

**Comment by Humber-186** [comment]
还有下边这两个参数决定着整个仿真时间中，哪一时间段的仿真将输出波形fst文件，其余仿真时间将不输出波形以提高仿真速度
```cpp
constexpr uint64_t SIM_WAVEFORM_TIME_BEGIN = 640000;
constexpr uint64_t SIM_WAVEFORM_TIME_END   = -1;
```
若要输出波形FST，需确认`SIM_WAVEFORM_TIME_BEGIN` ＜ `SIM_WAVEFORM_TIME_END`

**Comment by Humber-186** [comment]
另，此例中仿真在338992 ns结束，而`SIM_WAVEFORM_TIME_BEGIN = 640000`导致无波形输出，需调整

**Comment by xiaokaijia1988** [comment]
现在这个仿真需要多少周期能完成？

**Comment by xiaokaijia1988** [comment]
> 另，此例中仿真在338992 ns结束，而`SIM_WAVEFORM_TIME_BEGIN = 640000`导致无波形输出，需调整
现在这个仿真需要多少周期能完成？

**Comment by Humber-186** [comment]
就是log最末显示的338992
