### ISSUE TITLE
hello_test2 in ventus/tests/src/tests.scala 

### ISSUE THREAD

**Issue by wuliJerry** [THU-DSP-LAB/ventus-gpgpu#8]
Can these test benches run using any other simulator backend besides Treadle provided by chiseltest like Icarus and Veilator? Simulating with `IcarusBackendAnnotation` will generate a lot of Error messages. Is there any way to run simulations using these simulators?

**Comment by yangkex** [comment]
Now there are known bugs in RegisterFile and some other modules, so maybe simulation error is not because of your simulator backend. After fixing them we'll test other simulator backend.

**Comment by yangkex** [comment]
Now VCD files can generate successfully with Treadle backend.

> Now there are known bugs in RegisterFile and some other modules, so maybe simulation error is not because of your simulator backend. After fixing them we'll test other simulator backend.
